cc_library(
    name = "koala_core",
    srcs = [
        "async.c",
        "types.c",
        "math/mathemetica.c",
    ],
    hdrs = [
        "async.h",
        "types.h",
        "math/mathematica.h",
    ],
    includes = ["."],
    visibility = ["//visibility:public"],
) 