#ifndef KOALA_H
#define KOALA_H

#define KOALA_VERSION_MAJOR 1
#define KOALA_VERSION_MINOR 0
#define KOALA_VERSION_PATCH 0

#define LIBRARY_NAME "koala"
#define LIBRARY_VERSION (KOALA_VERSION_MAJOR * 10000 + KOALA_VERSION_MINOR * 100 + KOALA_VERSION_PATCH)


#endif // KOALA_H