Koala: Логгер AntLogger
Логгер AntLogger
Многофункциональный потокобезопасный логгер с поддержкой асинхронности, модулей и цветного вывода.
Data Structures
struct AntLogAsyncMsg
Структура для передачи лог-сообщения в event loop.
Functions
void ant_log_enable_colors (bool enable)
Включить или отключить цветной вывод.
void ant_log_enable_async (bool enable)
Включить или отключить асинхронный режим логирования.
void ant_log_init (const char *file_path)
Инициализация логгера.
void ant_log_shutdown ()
Завершение работы логгера, освобождение ресурсов.
void ant_log_set_level (ant_log_level_t level)
Установить минимальный уровень логирования.
void ant_log_set_callback (ant_log_callback_t cb)
Установить пользовательский callback для логирования.
static void ant_log_output (ant_log_level_t level, const char *module, const char *msg)
Вывод сообщения (thread-safe)
static void ant_log_format (char *out, size_t out_sz, ant_log_level_t level, const char *module, const char *file, int line, const char *func, const char *msg)
Форматирование сообщения с цветом, временем и контекстом.
static Result ant_log_async_func (FunctionParams *params)
Функция-обёртка для асинхронного вывода логов через event loop.
void ant_log_write (ant_log_level_t level, const char *module, const char *file, int line, const char *func, const char *fmt,...)
Основная функция логирования (используйте макросы).
Variables
static FILE * log_file = NULL
Файл для логирования (NULL = stderr)
static ant_log_level_t min_level = ANT_LOG_DEBUG
Минимальный уровень логирования
static ant_log_callback_t user_callback = NULL
Пользовательский callback для логирования
static int use_colors = 1
Включён ли цветной вывод
static int use_async = 0
Включён ли асинхронный режим
static AsyncEventLoop * log_loop = NULL
Event loop для асинхронного логирования
static pthread_mutex_t log_mutex = PTHREAD_MUTEX_INITIALIZER
Мьютекс для потокобезопасности
static const char * level_colors []
static const char * level_names []
Detailed Description
Многофункциональный потокобезопасный логгер с поддержкой асинхронности, модулей и цветного вывода.
Function Documentation
ant_log_async_func()
static Result ant_log_async_func (FunctionParams * params) static
Функция-обёртка для асинхронного вывода логов через event loop.
Definition at line 174 of file ant_logger.c.
{
    if (!params || !params->argv || params->argc < 1) {
        fprintf(stderr, "[ant_logger] ERROR: Invalid async log parameters!\n");
        return (Result){ .is_ok = 0 };
    }
    AntLogAsyncMsg* logmsg = (AntLogAsyncMsg*)params->argv[0].value;
    if (!logmsg) {
        fprintf(stderr, "[ant_logger] ERROR: NULL log message in async!\n");
        return (Result){ .is_ok = 0 };
    }
    ant_log_output(logmsg->level, logmsg->module, logmsg->message);
    free(logmsg);
    free(params->argv);
    free(params);
    return (Result){ .is_ok = 1 };
}
References ant_log_output(), FunctionParams::argc, FunctionParams::argv, AntLogAsyncMsg::level, AntLogAsyncMsg::message, AntLogAsyncMsg::module, and Generic::value.
Referenced by ant_log_write().
ant_log_enable_async()
void ant_log_enable_async (bool enable)
Включить или отключить асинхронный режим логирования.
Асинхронный режим (по умолчанию выключен)
Parameters
enable 1 - включить, 0 - отключить
Definition at line 69 of file ant_logger.c.
{
    if (enable && !use_async) {
        log_loop = async_event_loop_init();
        if (!log_loop) {
            fprintf(stderr, "[ant_logger] ERROR: Failed to initialize async event loop!\n");
            return;
        }
        use_async = 1;
    } else if (!enable && use_async) {
        async_event_loop_stop(log_loop);
        log_loop = NULL;
        use_async = 0;
    }
}
References async_event_loop_init(), async_event_loop_stop(), log_loop, and use_async.
ant_log_enable_colors()
void ant_log_enable_colors (bool enable)
Включить или отключить цветной вывод.
Цветной вывод (по умолчанию включён для терминала)
Parameters
enable 1 - включить, 0 - отключить
Definition at line 63 of file ant_logger.c.
{ use_colors = enable ? 1 : 0; }
References use_colors.
ant_log_format()
static void ant_log_format (char * out, size_t out_sz, ant_log_level_t level, const char * module, const char * file, int line, const char * func, const char * msg) static
Форматирование сообщения с цветом, временем и контекстом.
Definition at line 154 of file ant_logger.c.
{
    char timebuf[32];
    time_t now = time(NULL);
    struct tm* tm_info = localtime(&now);
    strftime(timebuf, sizeof(timebuf), "%Y-%m-%d %H:%M:%S", tm_info);
    if (use_colors) {
        snprintf(out, out_sz, "%s[%s] [%s] [%s] %s:%d (%s): %s\033[0m\n",
            level_colors[level], timebuf, level_names[level], module, file, line, func, msg);
    } else {
        snprintf(out, out_sz, "[%s] [%s] [%s] %s:%d (%s): %s\n",
            timebuf, level_names[level], module, file, line, func, msg);
    }
}
References level_colors, level_names, and use_colors.
Referenced by ant_log_write().
ant_log_init()
void ant_log_init (const char * file_path)
Инициализация логгера.
Инициализация логгера (опционально: путь к файлу, callback)
Parameters
file_path Путь к файлу для логирования (NULL = stderr)
Definition at line 88 of file ant_logger.c.
{
    if (file_path) {
        log_file = fopen(file_path, "a");
        if (!log_file) {
            fprintf(stderr, "[ant_logger] ERROR: Failed to open log file '%s'! Logging to stderr.\n", file_path);
            log_file = NULL;
        }
    }
}
References log_file.
ant_log_output()
static void ant_log_output (ant_log_level_t level, const char * module, const char * msg) static
Вывод сообщения (thread-safe)
Definition at line 136 of file ant_logger.c.
{
    pthread_mutex_lock(&log_mutex);
    if (user_callback) {
        user_callback(level, module, msg);
    } else {
        if (log_file) {
            fputs(msg, log_file);
            fflush(log_file);
        } else {
            fputs(msg, stderr);
        }
    }
    pthread_mutex_unlock(&log_mutex);
}
References log_file, log_mutex, and user_callback.
Referenced by ant_log_async_func(), and ant_log_write().
ant_log_set_callback()
void ant_log_set_callback (ant_log_callback_t cb)
Установить пользовательский callback для логирования.
Parameters
cb Callback-функция
Definition at line 121 of file ant_logger.c.
{ user_callback = cb; }
References user_callback.
ant_log_set_level()
void ant_log_set_level (ant_log_level_t level)
Установить минимальный уровень логирования.
Установить минимальный уровень логирования
Parameters
level Минимальный уровень
Definition at line 115 of file ant_logger.c.
{ min_level = level; }
References min_level.
ant_log_shutdown()
void ant_log_shutdown ()
Завершение работы логгера, освобождение ресурсов.
Завершение работы логгера (закрытие файлов и т.д.)
Definition at line 101 of file ant_logger.c.
{
    if (log_file) fclose(log_file);
    log_file = NULL;
    if (use_async && log_loop) {
        async_event_loop_stop(log_loop);
        log_loop = NULL;
        use_async = 0;
    }
}
References async_event_loop_stop(), log_file, log_loop, and use_async.
ant_log_write()
void ant_log_write (ant_log_level_t level, const char * module, const char * file, int line, const char * func, const char * fmt, ...)
Основная функция логирования (используйте макросы).
Основная функция логирования (не используйте напрямую, используйте макросы)
Parameters
level Уровень
module Модуль
file Файл
line Строка
func Функция
fmt Формат
... Аргументы
Definition at line 201 of file ant_logger.c.
{
    if (level < min_level) return;
    if (!module || !file || !func || !fmt) {
        fprintf(stderr, "[ant_logger] ERROR: Invalid log parameters!\n");
        return;
    }
    char user_msg[ANT_LOG_MAX_MSG];
    va_list args;
    va_start(args, fmt);
    vsnprintf(user_msg, sizeof(user_msg), fmt, args);
    va_end(args);
    char final_msg[ANT_LOG_MAX_MSG];
    ant_log_format(final_msg, sizeof(final_msg), level, module, file, line, func, user_msg);
    if (use_async && log_loop) {
        AntLogAsyncMsg* logmsg = (AntLogAsyncMsg*)malloc(sizeof(AntLogAsyncMsg));
        if (!logmsg) {
            fprintf(stderr, "[ant_logger] ERROR: Out of memory for async log!\n");
            return;
        }
        logmsg->level = level;
        strncpy(logmsg->module, module, ANT_LOG_MAX_MODULE-1);
        logmsg->module[ANT_LOG_MAX_MODULE-1] = 0;
        strncpy(logmsg->message, final_msg, ANT_LOG_MAX_MSG-1);
        logmsg->message[ANT_LOG_MAX_MSG-1] = 0;
        // Подготовка параметров для event loop
        FunctionParams* params = (FunctionParams*)malloc(sizeof(FunctionParams));
        if (!params) {
            fprintf(stderr, "[ant_logger] ERROR: Out of memory for async params!\n");
            free(logmsg);
            return;
        }
        params->argc = 1;
        params->argv = (Generic*)malloc(sizeof(Generic));
        if (!params->argv) {
            fprintf(stderr, "[ant_logger] ERROR: Out of memory for async argv!\n");
            free(logmsg);
            free(params);
            return;
        }
        params->argv[0].value = logmsg;
        params->argv[0].type = GENERIC_TYPE_PTR;
        FunctionPipeline* fp = (FunctionPipeline*)malloc(sizeof(FunctionPipeline));
        if (!fp) {
            fprintf(stderr, "[ant_logger] ERROR: Out of memory for async pipeline!\n");
            free(logmsg);
            free(params->argv);
            free(params);
            return;
        }
        fp->func = ant_log_async_func;
        fp->next = NULL;
        async_run(log_loop, fp, params);
    } else {
        ant_log_output(level, module, final_msg);
    }
}
References ant_log_async_func(), ant_log_format(), ANT_LOG_MAX_MODULE, ANT_LOG_MAX_MSG, ant_log_output(), FunctionParams::argc, FunctionParams::argv, async_run(), FunctionPipeline::func, GENERIC_TYPE_PTR, AntLogAsyncMsg::level, log_loop, AntLogAsyncMsg::message, min_level, AntLogAsyncMsg::module, FunctionPipeline::next, Generic::type, use_async, and Generic::value.
Variable Documentation
level_colors
const char* level_colors[] static
Initial value:
= {
    "\033[0;37m",
    "\033[0;32m",
    "\033[1;33m",
    "\033[0;31m",
    "\033[1;41m"
}
Definition at line 48 of file ant_logger.c.
{
    "\033[0;37m", // DEBUG - white
    "\033[0;32m", // INFO - green
    "\033[1;33m", // WARNING - yellow
    "\033[0;31m", // ERROR - red
    "\033[1;41m"  // FATAL - red bg
};
Referenced by ant_log_format().
level_names
const char* level_names[] static
Initial value:
= {
    "DEBUG", "INFO", "WARNING", "ERROR", "FATAL"
}
Definition at line 55 of file ant_logger.c.
{
    "DEBUG", "INFO", "WARNING", "ERROR", "FATAL"
};
Referenced by ant_log_format().
log_file
FILE* log_file = NULL static
Файл для логирования (NULL = stderr)
Definition at line 22 of file ant_logger.c.
Referenced by ant_log_init(), ant_log_output(), and ant_log_shutdown().
log_loop
AsyncEventLoop* log_loop = NULL static
Event loop для асинхронного логирования
Definition at line 42 of file ant_logger.c.
Referenced by ant_log_enable_async(), ant_log_shutdown(), and ant_log_write().
log_mutex
pthread_mutex_t log_mutex = PTHREAD_MUTEX_INITIALIZER static
Мьютекс для потокобезопасности
Definition at line 46 of file ant_logger.c.
Referenced by ant_log_output().
min_level
ant_log_level_t min_level = ANT_LOG_DEBUG static
Минимальный уровень логирования
Definition at line 26 of file ant_logger.c.
Referenced by ant_log_set_level(), and ant_log_write().
use_async
int use_async = 0 static
Включён ли асинхронный режим
Definition at line 38 of file ant_logger.c.
Referenced by ant_log_enable_async(), ant_log_shutdown(), and ant_log_write().
use_colors
int use_colors = 1 static
Включён ли цветной вывод
Definition at line 34 of file ant_logger.c.
Referenced by ant_log_enable_colors(), and ant_log_format().
user_callback
ant_log_callback_t user_callback = NULL static
Пользовательский callback для логирования
Definition at line 30 of file ant_logger.c.
Referenced by ant_log_output(), and ant_log_set_callback().