Koala: core/math/mathemetica.c File Reference
mathemetica.c File Reference
#include "mathematica.h"
#include <stdlib.h>
Functions
static Vector * create_node (Generic *data)
void push (struct Vector *vec, Generic *data)
Добавить элемент в конец вектора.
void delete (struct Vector *vec)
Удалить все элементы вектора и освободить память.
void free_vector (struct Vector *vec)
Освободить память, занятую вектором (синоним delete).
Vector * allocate_memory_for_vector ()
Выделить память под новый вектор (используется внутри init_vector).
Vector * init_vector ()
Инициализировать новый пустой вектор.
Function Documentation
allocate_memory_for_vector()
Vector * allocate_memory_for_vector ()
Выделить память под новый вектор (используется внутри init_vector).
Returns
Указатель на новый вектор или NULL при ошибке
Definition at line 52 of file mathemetica.c.
{
    Vector* vec = (Vector*)malloc(sizeof(Vector));
    if (!vec) return NULL;
    vec->data = NULL;
    vec->next = NULL;
    vec->push_back = push;
    return vec;
}
References Vector::data, Vector::next, push(), and Vector::push_back.
Referenced by init_vector().
create_node()
static Vector * create_node (Generic * data) static
Definition at line 5 of file mathemetica.c.
{
    Vector* node = (Vector*)malloc(sizeof(Vector));
    if (!node) return NULL;
    node->data = data;
    node->next = NULL;
    node->push_back = push;
    return node;
}
References Vector::data, Vector::next, push(), and Vector::push_back.
Referenced by push().
delete()
void delete (struct Vector * vec)
Удалить все элементы вектора и освободить память.
Parameters
vec Указатель на вектор
Definition at line 33 of file mathemetica.c.
{
    if (!vec) return;
    Vector* current = vec;
    Vector* prev = NULL;
    while (current) {
        Vector* next = current->next;
        free(current);
        current = next;
    }
}
References Vector::next.
free_vector()
void free_vector (struct Vector * vec)
Освободить память, занятую вектором (синоним delete).
Parameters
vec Указатель на вектор
Definition at line 47 of file mathemetica.c.
{
    delete(vec); // Just alias to delete in this implementation
}
init_vector()
Vector * init_vector ()
Инициализировать новый пустой вектор.
Returns
Указатель на новый вектор или NULL при ошибке
Definition at line 63 of file mathemetica.c.
                      {
    Vector* vec = allocate_memory_for_vector();
    return vec;
}
References allocate_memory_for_vector().
push()
void push (struct Vector * vec, Generic * data)
Добавить элемент в конец вектора.
Parameters
vec Указатель на вектор
data Указатель на объект Generic
Definition at line 16 of file mathemetica.c.
{
    if (!vec) return;
    // Find the last node
    Vector* current = vec;
    while (current->next) {
        current = current->next;
    }
    // Create and append new node
    Vector* new_node = create_node(data);
    if (!new_node) return;
    current->next = new_node;
}
References create_node(), and Vector::next.
Referenced by allocate_memory_for_vector(), and create_node().