Koala: external/milenadb/src/milena_queue.cpp File Reference
milena_queue.cpp File Reference
#include "milena_queue.h"
#include <string>
#include <vector>
#include <memory>
Data Structures
struct TaskCpp
struct Queue
Очередь задач (реализация скрыта в C++, opaque pointer для C).
Functions
Queue * queue_create ()
Создать новую очередь задач.
void queue_destroy (Queue *q)
Удалить очередь и освободить всю связанную с ней память.
void queue_append (Queue *q, const Task *task)
Добавить задачу в конец очереди.
int queue_remove_by_index (Queue *q, int index)
Удалить задачу по индексу из очереди.
int queue_size (const Queue *q)
Получить количество задач в очереди.
const Task * queue_get (const Queue *q, int index)
Получить задачу по индексу.
Function Documentation
queue_append()
void queue_append (Queue * q, const Task * task)
Добавить задачу в конец очереди.
Parameters
q Указатель на очередь
task Указатель на структуру Task
Task t = {"Task1", "echo Hello", 1, TASK_PENDING};
queue_append(q, &t);
Definition at line 37 of file milena_queue.cpp.
{
    if (q && task) {
        q->tasks.emplace_back(*task);
    }
}
References Queue::tasks.
Referenced by main().
queue_create()
Queue * queue_create ()
Создать новую очередь задач.
Returns
Указатель на очередь (Queue*) или NULL при ошибке.
Queue* q = queue_create();
Definition at line 29 of file milena_queue.cpp.
                      {
    return new Queue();
}
Referenced by main().
queue_destroy()
void queue_destroy (Queue * q)
Удалить очередь и освободить всю связанную с ней память.
Parameters
q Указатель на очередь
queue_destroy(q);
Definition at line 33 of file milena_queue.cpp.
{
    delete q;
}
Referenced by main().
queue_get()
const Task * queue_get (const Queue * q, int index)
Получить задачу по индексу.
Parameters
q Указатель на очередь
index Индекс задачи (начиная с 0)
Returns
Указатель на задачу (Task*) или NULL, если индекс некорректен
const Task* t = queue_get(q, 0);
Definition at line 53 of file milena_queue.cpp.
{
    if (!q || index < 0 || index >= (int)q->tasks.size()) return nullptr;
    // ВНИМАНИЕ: возвращаем временный Task, который живёт до конца функции!
    // Для реального API лучше возвращать копию через out-параметр.
    static thread_local Task temp;
    temp = q->tasks[index].to_c();
    return &temp;
}
References Queue::tasks.
Referenced by main().
queue_remove_by_index()
int queue_remove_by_index (Queue * q, int index)
Удалить задачу по индексу из очереди.
Parameters
q Указатель на очередь
index Индекс задачи (начиная с 0)
Returns
1 если задача удалена, 0 если индекс некорректен
queue_remove_by_index(q, 2);
Definition at line 43 of file milena_queue.cpp.
{
    if (!q || index < 0 || index >= (int)q->tasks.size()) return 0;
    q->tasks.erase(q->tasks.begin() + index);
    return 1;
}
References Queue::tasks.
Referenced by main().
queue_size()
int queue_size (const Queue * q)
Получить количество задач в очереди.
Parameters
q Указатель на очередь
Returns
Количество задач (>=0)
int n = queue_size(q);
Definition at line 49 of file milena_queue.cpp.
{
    return q ? (int)q->tasks.size() : 0;
}
References Queue::tasks.
Referenced by main().